// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// boin_simulate_cpp
List boin_simulate_cpp(int n_trials, NumericVector p_true, IntegerVector cohort_size, int start_dose, int n_earlystop, bool early_stop_simple, bool titration, bool extrasafe, double target, double cutoff_eli, double offset, IntegerVector b_esc, IntegerVector b_deesc, IntegerVector b_elim, int max_total_pts);
RcppExport SEXP _simFastBOIN_boin_simulate_cpp(SEXP n_trialsSEXP, SEXP p_trueSEXP, SEXP cohort_sizeSEXP, SEXP start_doseSEXP, SEXP n_earlystopSEXP, SEXP early_stop_simpleSEXP, SEXP titrationSEXP, SEXP extrasafeSEXP, SEXP targetSEXP, SEXP cutoff_eliSEXP, SEXP offsetSEXP, SEXP b_escSEXP, SEXP b_deescSEXP, SEXP b_elimSEXP, SEXP max_total_ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_trials(n_trialsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_true(p_trueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cohort_size(cohort_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type start_dose(start_doseSEXP);
    Rcpp::traits::input_parameter< int >::type n_earlystop(n_earlystopSEXP);
    Rcpp::traits::input_parameter< bool >::type early_stop_simple(early_stop_simpleSEXP);
    Rcpp::traits::input_parameter< bool >::type titration(titrationSEXP);
    Rcpp::traits::input_parameter< bool >::type extrasafe(extrasafeSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_eli(cutoff_eliSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b_esc(b_escSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b_deesc(b_deescSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b_elim(b_elimSEXP);
    Rcpp::traits::input_parameter< int >::type max_total_pts(max_total_ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(boin_simulate_cpp(n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, titration, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts));
    return rcpp_result_gen;
END_RCPP
}
// boin_select_mtd_cpp
List boin_select_mtd_cpp(IntegerMatrix n_pts, IntegerMatrix n_tox, double target, double cutoff_eli, bool extrasafe, double offset, bool bound_mtd, double lambda_d, int min_mtd_sample);
RcppExport SEXP _simFastBOIN_boin_select_mtd_cpp(SEXP n_ptsSEXP, SEXP n_toxSEXP, SEXP targetSEXP, SEXP cutoff_eliSEXP, SEXP extrasafeSEXP, SEXP offsetSEXP, SEXP bound_mtdSEXP, SEXP lambda_dSEXP, SEXP min_mtd_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type n_pts(n_ptsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type n_tox(n_toxSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_eli(cutoff_eliSEXP);
    Rcpp::traits::input_parameter< bool >::type extrasafe(extrasafeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type bound_mtd(bound_mtdSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_d(lambda_dSEXP);
    Rcpp::traits::input_parameter< int >::type min_mtd_sample(min_mtd_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(boin_select_mtd_cpp(n_pts, n_tox, target, cutoff_eli, extrasafe, offset, bound_mtd, lambda_d, min_mtd_sample));
    return rcpp_result_gen;
END_RCPP
}
// boin_isotonic_cpp
NumericMatrix boin_isotonic_cpp(IntegerMatrix n_pts, IntegerMatrix n_tox, LogicalMatrix admissible);
RcppExport SEXP _simFastBOIN_boin_isotonic_cpp(SEXP n_ptsSEXP, SEXP n_toxSEXP, SEXP admissibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type n_pts(n_ptsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type n_tox(n_toxSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type admissible(admissibleSEXP);
    rcpp_result_gen = Rcpp::wrap(boin_isotonic_cpp(n_pts, n_tox, admissible));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simFastBOIN_boin_simulate_cpp", (DL_FUNC) &_simFastBOIN_boin_simulate_cpp, 15},
    {"_simFastBOIN_boin_select_mtd_cpp", (DL_FUNC) &_simFastBOIN_boin_select_mtd_cpp, 9},
    {"_simFastBOIN_boin_isotonic_cpp", (DL_FUNC) &_simFastBOIN_boin_isotonic_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_simFastBOIN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
