#' Convert TITE-BOIN Decision Table to Simulation Format
#'
#' @description
#' Convert the TITE-BOIN decision table from \code{get_titeboin_decision()} to a
#' simulation-optimized format. This function extracts numeric thresholds from
#' decision conditions (e.g., "MF<0.25", "STFT>=2.5") and adds flags for easier
#' lookup during trial simulation.
#'
#' The converted format allows for efficient decision-making during simulation by
#' pre-extracting:
#' \itemize{
#'   \item Missing Fraction (MF) thresholds
#'   \item Standardized Total Follow-up Time (STFT) thresholds
#'   \item Elimination flags
#' }
#'
#' @param dt_decision A decision table generated by \code{get_titeboin_decision()}
#'
#' @return A data frame with the same structure as the input, plus additional columns:
#' \describe{
#'   \item{obs_rate}{Observed toxicity rate (n_tox / n_patients)}
#'   \item{mf_threshold}{Numeric Missing Fraction threshold extracted from conditions}
#'   \item{stft_threshold}{Numeric STFT threshold extracted from conditions}
#'   \item{eliminate_flag}{Logical flag indicating if dose should be eliminated}
#' }
#'
#' @details
#' This function uses regular expressions to parse the decision conditions and extract
#' numeric thresholds. The resulting table enables fast lookups during simulation,
#' improving computational efficiency for large-scale Monte Carlo studies.
#'
#' @references
#' Yuan, Y., Lin, R., Li, D., Nie, L. and Warren, K.E. (2018).
#' Time-to-Event Bayesian Optimal Interval Design to Accelerate Phase I Trials.
#' Clinical Cancer Research, 24(20): 4921-4930.
#'
#' @importFrom dplyr %>% mutate arrange case_when
#' @importFrom stringr str_detect str_extract
#'
#' @examples
#' # Generate TITE-BOIN decision table
#' target <- 0.30
#' boundary <- get_boin_boundary(target)
#'
#' dt_full <- get_titeboin_decision(
#'   lambda_e = boundary$lambda_e,
#'   lambda_d = boundary$lambda_d,
#'   target = target,
#'   n_max = 18,
#'   cohort_size = 3
#' )
#'
#' # Convert to simulation format
#' dt_sim <- convert_titeboin_decision_to_sim_format(dt_full)
#'
#' # View structure
#' head(dt_sim)
#' names(dt_sim)
#'
#' @seealso \code{\link{get_titeboin_decision}} for generating the decision table
#'
#' @export
convert_titeboin_decision_to_sim_format <- function(dt_decision) {
  
  dt_decision %>%
    mutate(
      obs_rate = n_tox / n_patients,
      mf_threshold = case_when(
        str_detect(suspend, "MF<") ~ as.numeric(str_extract(suspend, "(?<=MF<)\\d+\\.\\d+")),
        TRUE ~ NA_real_),
      stft_threshold = case_when(
        str_detect(suspend, "STFT>=") ~ as.numeric(str_extract(suspend, "(?<=STFT>=)\\d+\\.\\d+")),
        str_detect(escalate, "STFT>=") ~ as.numeric(str_extract(escalate, "(?<=STFT>=)\\d+\\.\\d+")),
        str_detect(stay, "STFT<") ~ as.numeric(str_extract(stay, "(?<=STFT<)\\d+\\.\\d+")),
        str_detect(stay, "STFT>") ~ as.numeric(str_extract(stay, "(?<=STFT>)\\d+\\.\\d+")),
        str_detect(de_escalate, "STFT<=") ~ as.numeric(str_extract(de_escalate, "(?<=STFT<=)\\d+\\.\\d+")),
        TRUE ~ NA_real_),
      eliminate_flag = str_detect(de_escalate, "Eliminate")
    ) %>%
    arrange(n_patients, n_tox, n_pending)
}