# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boin_simulate_cpp <- function(n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, titration, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts) {
    .Call(`_simFastBOIN_boin_simulate_cpp`, n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, titration, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts)
}

boin_select_mtd_cpp <- function(n_pts, n_tox, target, cutoff_eli, extrasafe, offset, bound_mtd, lambda_d, min_mtd_sample) {
    .Call(`_simFastBOIN_boin_select_mtd_cpp`, n_pts, n_tox, target, cutoff_eli, extrasafe, offset, bound_mtd, lambda_d, min_mtd_sample)
}

boin_isotonic_cpp <- function(n_pts, n_tox, admissible) {
    .Call(`_simFastBOIN_boin_isotonic_cpp`, n_pts, n_tox, admissible)
}

tite_boin_simulate_cpp <- function(n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts, method, lambda_e, lambda_d, max_pending_ratio, min_completed, min_follow_up, window, accrual, accrual_rate, dlt_time, late_fraction, weighted, prior_weights, stream_seed) {
    .Call(`_simFastBOIN_tite_boin_simulate_cpp`, n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts, method, lambda_e, lambda_d, max_pending_ratio, min_completed, min_follow_up, window, accrual, accrual_rate, dlt_time, late_fraction, weighted, prior_weights, stream_seed)
}

tite_decision_cpp <- function(n, n_tox, n_pending, stft, mf, method, target, lambda_e, lambda_d, max_pending_ratio, min_completed, min_follow_up, b_esc, b_deesc, b_elim) {
    .Call(`_simFastBOIN_tite_decision_cpp`, n, n_tox, n_pending, stft, mf, method, target, lambda_e, lambda_d, max_pending_ratio, min_completed, min_follow_up, b_esc, b_deesc, b_elim)
}

