# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boin_simulate_cpp <- function(n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, titration, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts) {
    .Call(`_simFastBOIN_boin_simulate_cpp`, n_trials, p_true, cohort_size, start_dose, n_earlystop, early_stop_simple, titration, extrasafe, target, cutoff_eli, offset, b_esc, b_deesc, b_elim, max_total_pts)
}

boin_select_mtd_cpp <- function(n_pts, n_tox, target, cutoff_eli, extrasafe, offset, bound_mtd, lambda_d, min_mtd_sample) {
    .Call(`_simFastBOIN_boin_select_mtd_cpp`, n_pts, n_tox, target, cutoff_eli, extrasafe, offset, bound_mtd, lambda_d, min_mtd_sample)
}

boin_isotonic_cpp <- function(n_pts, n_tox, admissible) {
    .Call(`_simFastBOIN_boin_isotonic_cpp`, n_pts, n_tox, admissible)
}

